### PR TITLE
Migrate mutex library to non nullable by default safe code.

### PR DESCRIPTION
**Pull request by creativepsyco**
https://github.com/dart-lang/sdk/tree/master/pkg/nnbd_migration

Also removed some of the asserts since they are not needed in the NNBD world.

### CODE REVIEW

**Comment by hoylen** [comment]
Excellent work. Thank you Mohit.

I'm looking forward to _null safety_ and will merge this in, and make a release to pub.dev, after the feature is available in production Dart. Unless there is a good reason to do it earlier.

**Comment by creativepsyco** [comment]
We use this library within google and since we compile everything from source, at least the master branch can be merged with this change without publishing to pub.dev so that we can mirror this internally and update to NNBD.

During beta however, if you want to publish to pub.dev you can also do so, as there might be downward clients and dependencies on this library who would want to migrate to nullsafety, this gives them an option to do so. 

Based on [Migration instructions][1] I have added a `-nullsafety-0` suffix and bumped the major version. This can now be published to pub.dev as a pre-release version while NNBD is still in beta.

[1]: https://kw-www-dartlang-1.firebaseapp.com/null-safety/migration-guide#update-dependencies

**Comment by hoylen** [comment]
Ok. I've merged it into master.

I'll have a closer look at it before publishing a _-nullsafety_ release to _pub.dev_.

Thank you once again.

**Comment by creativepsyco** [comment]
Awesome thanks!

**Pull request merged**
